app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: 'https://idp.kendrasustain.com'

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: 'https://idp.kendrasustain.com'
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen:
    port: 7007
    host: 0.0.0.0

  # config options: https://node-postgres.com/api/client
  csp:
    connect-src: ["'self'", "http:", "https:"]
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false

  cors:
    origin: 'https://idp.kendrasustain.com'
    #methods: [GET, POST, PUT, DELETE]
    #credentials: true
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: db #${POSTGRES_HOST}
      port:  5432 #${POSTGRES_PORT}
      user: postgres #${POSTGRES_USER}
      password: password #${POSTGRES_PASSWORD}
    # ensureExists: true
    pluginDivisionMode: schema

  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

techdocs:
  builder: "external" # Alternatives - 'external'
  # generator:
  #   runIn: 'docker'
  publisher:
    type: "awsS3"
    awsS3:
      bucketName: ${TECHDOCS_BUCKET}
      region: ${AWS_REGION}
      credentials:
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  locations: []
