version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backstage:
    image: nitin03/backstage
    restart: always
    ports:
      - 7007:7007
    volumes:
      - ${PWD}/github-app-backstage-mybackstageapp-credentials.yaml:/app/github-app-backstage-mybackstageapp-credentials.yaml
    environment:
      - POSTGRES_HOST=db  # Connect to the 'db' service within the same network
      - POSTGRES_PORT=5432  # Default PostgreSQL port
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_GITHUB_CLIENT_ID=${AUTH_GITHUB_CLIENT_ID}
      - AUTH_GITHUB_CLIENT_SECRET=${AUTH_GITHUB_CLIENT_SECRET}

networks:
  default:  # This creates a default bridge network for the services to communicate